- .eslintrc
- .gitignore
- package.json
- src/client/AccountsClient.js
- src/client/store.js
- src/common/AccountsCommon.js
- src/common/toUsernameAndEmail.js
- src/server/AccountsServer.spec.js
Trying to accelerate and get some feedback on the flow typings. 
@TimMikeladze  I branched off from your flow branch. 
Hopefully everything was pushed and there is no merges.. anyhow, let me know if that's the case and I'll work on the necessary changes.
> chore(flow): Added type declarations for accounts and made eslint and flow check happy

- packages/server/src/AccountsServer.js
- packages/server/src/AccountsServer.spec.js
- packages/server/src/DBInterface.js
This PR introduces a variety of improvements to the user session code and also adds support for user profiles.
> Sessions and user info

- CONTRIBUTING.md
Noticed a few things that might spice up the contribute doc.
- Markdown files can have anchor links, so I thought I'd update the "getting started" to point to what it was referencing. 
- Grammar improvements: title capitalization and it's vs its.
- "All PRs:" was asking to become a header due to the colon and followed list.
Is the section about the changelog still pertinent?
> Change: improve CONTRIBUTE.md

- README.md
- packages/common/src/config.js
- packages/server/package.json
- packages/server/src/AccountsServer.js
- packages/server/src/AccountsServer.spec.js
- packages/server/src/DBInterface.js
- packages/server/src/email.js
- packages/server/src/emailTemplates.js
- packages/server/src/tokens.js
- packages/server/yarn.lock
#40 
Setup email part.
Add siteUrl in config to construct absolute urls for email.
Add sendVerificationEmail.
Add sendResetPasswordEmail.
To overwrite the email templates:
```javascript
AccountsServer.config({
siteUrl: 'https://my-app.com',
email: // a valid email config object passed to emailjs
// https://github.com/eleith/emailjs#example-usage---text-only-emails
});
AccountsServer.emailTemplates.from = 'my-app <no-reply@my-app.com>';
AccountsServer.emailTemplates.verifyEmail.subject = (user) => `Verify your account email ${user.profile.lastname}`;
// Same for AccountsServer.emailTemplates.verifyEmail.text = (user, url)
```
> sendVerificationEmail and setup email

- packages/client/src/AccountsClient.js
- packages/client/src/config.js
- packages/client/src/index.js
This should not break use cases where the user does not have it's own redux store.
> Added an option to pass in a redux store

- packages/client/src/AccountsClient.js
- packages/client/src/AccountsClient.spec.js
> Add password recovery functions to client

- packages/client/src/AccountsClient.js
- packages/client/src/AccountsClient.spec.js
- packages/client/src/module.js
The goal is to have access to accessToken from Redux store, in order to know when there is available. This is also useful for accessing the token in a Redux-way.
At the moment, an app with Redux that need the accessToken needs to listen for `SET_USER` action, use async method `Accounts.tokens` and wait for the result.
> feat(redux-tokens): expose js-accounts tokens to redux store

- packages/client/src/AccountsClient.js
- packages/client/src/AccountsClient.spec.js
The goal is to load from the storage only once, when the app loads, and then use the inner redux store to manage the token in-memory. 
This way, we load the tokens eagerly from the storage when the `AccountsClient.config` called, and store them in-memory.
Also, the `tokens()` is always sync now, even if the storage is async (like with `AsyncStorage` of react-native)
> feat(tokens): eager load of tokens from storage

- packages/client/src/AccountsClient.js
- packages/client/src/AccountsClient.spec.js
- packages/client/src/config.js
Tried to create some distinction between resume session and refresh session.  The on resume session hook allows you to trigger actions via the hook that indicate first time log on.  For example, a user may wish to show a prompt to the user during initial log on.  To do so, they would attach the prompt to this on resume session hook.  signedInHook works too, but only captures initial login, not when the user uses tokens to re-authenticate. 
This has a corresponding change in rest package to change authFetch to call onRefreshSession (since this would typically be called after initial authentication)
> Make resume session with hook

- packages/server/src/AccountsServer.js
For some reason (maybe my bad CR for the impersonation PR) we were not checking for jwt token expiration.
> Impersonate check for access token without ignoring expiration

- packages/client/src/AccountsClient.js
- packages/client/src/AccountsClient.spec.js
- packages/client/src/config.js
When client impersonates, it's now possible to choose if to persist the impersonation state (and save it to the storage).
Configurable via `config`.
Also, fixed an issue with persisted impersonation: the original tokens need to be saved in the storage, and loaded when the client starts, in order to be able to return to the original tokens after refresh.
> feat(impersonation): added impersonation persistence optional

- packages/server/src/AccountsServer.js
- packages/server/src/AccountsServer.spec.js
- packages/server/src/config.js
First, we need to sanitize the User object, right before passing it to the client or external functions to avoid exposure of `services` array with the encrypted passwords.
Also, added to `options` the ability to provide another external sanitizer, so now the developer can filter fields before sending it to the client.
> feat(user-object-sanitizer): added user object sanitizer

- packages/server/src/AccountsServer.js
- packages/server/src/AccountsServer.spec.js
- packages/server/src/config.js
The goal is to provide the ability for the app to choose which login fields are allowed (id, username, email), and to forbid the rest of them.
> feat(allowed-login-fields): added ability to choose allowed login fields

- packages/client/src/AccountsClient.js
`PasswordLoginUserIdentityType` has username, email and id. 
`isValidUserObject()` was looking for a `user` key instead of `username`.
> Fix: invalid key in User object validation

- packages/server/src/accounts-server.ts
In some version of Meteor, the `services.password.reset` in an object, and in some an Array.
Also, in some versions the reset password token has an `address` field, and in some it's `email`. 
This PR includes fixes for both issues
> Fixes for reset password

- packages/server/src/accounts-server.ts
- packages/server/src/email.ts
TS does not auto import * when there is no default import. emailjs does not specify default import so it was broken since moving to TS.
> Fix missing import on email server

- .gitignore
- packages/common/src/types.ts
- packages/server/__tests__/accounts-server.ts
- packages/server/package.json
- packages/server/src/accounts-server.ts
- packages/server/src/index.ts
- packages/server/src/tokens.ts
- packages/server/src/types.ts
The goal of the pr is to change the information stored in the jwt. We are currently storing the sessionId which can be predictable, so if someone succeed to get your jwt secret, he will be able to impersonate any user you have and you will not notice it.
If we switch the session id with a random token which is not predictable we remove this potential security issue.
> use random tokens instead of sessionId inside sessions

- package.json
- packages/error/.npmignore
- packages/error/__tests__/accounts-error.ts
- packages/error/__tests__/index.ts
- packages/error/package.json
- packages/error/src/accounts-error.ts
- packages/error/src/index.ts
- packages/error/tsconfig.json
- yarn.lock
This is a first implementation of the AccountsError package.
````ts
new AccountsError('PasswordService','authenticate','no user match tokens')
// message => '[ Accounts - PasswordService ] authenticate : no user match tokens'
new AccountsError('no user match tokens')
// message => 'no user match tokens'
````
As the error code and login info is not used yet, I removed the code concerning them so we can implement it accordingly with the current state
> @accounts/error : new AccountsError package with message formatting

- packages/server/__tests__/account-server.ts
- packages/server/package.json
- packages/server/src/accounts-server.ts
- packages/server/src/index.ts
- packages/server/src/types/remove-listener-handle.ts
- packages/server/src/utils/server-hooks.ts
- packages/server/yarn.lock
- Use [Emittery](https://github.com/sindresorhus/emittery) instead of EventEmitter, this will allow us to wait for the emitters during the functions
- Remove all the `onXXX` functions so user will only use the `.on` function
For example so following code will prevent users with some invalid ip to connect to your application.
```javascript
accountsServer.on('Login', async ({ connection }) => {
if (!await isValid(connection.ip)) {
throw new Error('User not allowed')
}
});
// Can also be used to track services events
accountsServer.on('password.resetPassword', () => {
// Custom logic
});
```
> New hook system

- packages/client/src/accounts-client.ts
Actually refresh session does not return the tokens and throw if tokens are not in the cache when you call the function.
This make the client very verbose to setup:
```javascript
let tokens = await accounts.tokens();
if (tokens.accessToken) {
await accounts.refreshSession();
tokens = await accounts.tokens();
}
// now I can use the tokens
```
with that simple change this will reduce the code to
```javascript
const tokens = await accounts.refreshSession();
```
> Client refresh session return the tokens

- packages/server/src/types/send-mail-type.ts
- packages/types/src/types/hook-listener.ts
The `object` type does not let a user access the subfields of an object on strict mode so better use any here
> Fix HookListener and SendMailType definitions

- packages/client/src/accounts-client.ts
Currently we are trying to refresh the tokens even if the refresh token is expired which gave an error from the server as a response.
Quick fix for now on the current client implementation. Will also add it to the client refactor branch.
> Only refresh the tokens if refresh token is not expired on the client

- packages/server/__tests__/account-server.ts
- packages/server/src/accounts-server.ts
- packages/server/src/utils/server-hooks.ts
- `ServerHooks.LoginSuccess`
- `ServerHooks.LoginError`
With this change the 2 hooks will receive the following infos:
```
{
// The service name, such as “password” or “twitter”.
service
// The connection informations <ConnectionInformations>
connection
// The user object if set
user
}
```
I also renamed the `ServerHooks.Login` to `ServerHooks.ValidateLogin` because we let the user the ability to validate the current user on the login flow.
> Pass some context to the login hooks

- package.json
- packages/server/package.json
- yarn.lock
With TypeScript 2.9.1, current `@accounts/server` throws an error while compiling.
It's related to `emittery` package: sindresorhus/emittery/issues/34
Instead of asking a user to resolve to `emittery@0.4.0` I think `@accounts/server` should require the correct version that works fine.
Also, could it be released ASAP since it breaks apps with latest typescript?
> Update TypeScript and fix emittery issue

- packages/server/src/accounts-server.ts
When the user start the accounts server package warm him that the token is not secure.
> warm user in case of default token

- packages/graphql-api/README.md
- packages/graphql-api/package.json
- packages/graphql-api/src/index.ts
- packages/graphql-api/src/schema-builder.ts
- packages/graphql-api/src/utils/authenticated-directive.ts
- packages/graphql-api/src/utils/authenticated-resolver.ts
- packages/graphql-api/src/utils/context-builder.ts
- yarn.lock
Modifies createJSAccountsGraphQL to return typeDefs (renamed from schema), resolvers, and schemaDirectives.
Created AuthenticatedDirective which wraps all graphql objects or fields annotated with @authenticated.
**Todo**
**Questions**
- Should `@authenticated` to be renamed to `@auth` to be more concise?
- Should `createJSAccountsGraphQL` be renamed to `createAccountsGraphQL`?
**Related issues**: #362
> feat: @authenticated directive

- packages/graphql-client/package.json
- packages/graphql-client/src/graphql-client.ts
- yarn.lock
If we are executiong a refresh token mutation do not call refress session again otherwise it will end up in an infinite loop
> Fix infinite loop issue during token refresh for graphql-client

- packages/database-mongo/__tests__/index.ts
- packages/database-mongo/src/mongo.ts
- packages/password/__tests__/accounts-password.ts
- packages/password/package.json
- packages/password/src/accounts-password.ts
- packages/types/src/types/database-interface.ts
If we let it like this we will end up setting this string in all the database implementation, I think it's cleaner to make the parameter mandatory.
> Required reason token for the database interface

- packages/apollo-link-accounts/package.json
- packages/apollo-link-accounts/src/index.ts
- yarn.lock
Right now when we compile apollo-link-accounts we have this file (`index.d.ts`) which is generated and failing when you integrate it to your project.
```ts
import { AccountsClient } from '@accounts/client';
export declare const accountsLink: (accountsClient: AccountsClient) => import("../../../node_modules/apollo-link-context/node_modules/apollo-link/lib/link").ApolloLink;
```
after the fix:
```ts
import { ApolloLink } from 'apollo-link';
import { AccountsClient } from '@accounts/client';
export declare const accountsLink: (accountsClient: AccountsClient) => ApolloLink;
```
> Fix apollo-link-accounts types

- packages/password/package.json
As is, you get this warning with latest `@accounts/server`:
```
npm WARN @accounts/password@0.3.0-beta.21 requires a peer of @accounts/serve
r@^0.1.0-beta.0 but none is installed. You must install peer dependencies yo
urself.
```
> Update @accounts/password peer dep

- packages/graphql-api/src/index.ts
We need to extend from `IResolverContext` and merge in our own properties. So I wonder maybe `IResolverContext` should be exported.
> feat: export graphql-api types

- packages/server/__tests__/utils/__snapshots__/email.ts.snap
- packages/server/__tests__/utils/email.ts
- packages/server/src/accounts-server.ts
- packages/server/src/types/email-template-type.ts
- packages/server/src/utils/email.ts
I think it'll give a better idea to people of the existence of the option to have html if they see it printed to console or if they look at the code.
> Add html email templates

- packages/server/__tests__/account-server.ts
- packages/server/src/accounts-server.ts
This will allow us to save one query from the database.
You can access the user inside `ServerHooks.LogoutSuccess` event with `session.userId` and fetching it from the database.
> Do not fetch the user on logout

- packages/e2e/__tests__/servers/server-graphql.ts
- packages/graphql-api/src/resolvers/get-user.ts
- packages/graphql-api/src/utils/authenticated-resolver.ts
- packages/graphql-api/src/utils/context-builder.ts
Close #421 
The new context will now be async (breaking change)
> Load the user in the context resolver

- packages/database-mongo/__tests__/index.ts
- packages/database-mongo/package.json
- packages/database-mongo/src/mongo.ts
- packages/e2e/package.json
- yarn.lock
Fixes #462
Keeps retro-compatibility with mongodb 2.0
http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#updateOne
http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#updateOne
> [@accounts/mongo] Switched from collection.update to collection.updateOne

- packages/database-manager/__tests__/database-manager.ts
- packages/database-manager/src/database-manager.ts
- packages/database-mongo/__tests__/index.ts
- packages/database-mongo/src/mongo.ts
- packages/server/__tests__/__snapshots__/account-server.ts.snap
- packages/server/__tests__/account-server.ts
- packages/server/src/accounts-server.ts
- packages/types/src/types/database-interface.ts
- packages/types/src/types/user.ts
> [@accounts/server] Deactivate user

- packages/e2e/__tests__/password.ts
- packages/graphql-api/src/modules/accounts-password/index.ts
- packages/graphql-api/src/modules/accounts-password/resolvers/mutation.ts
- packages/password/__tests__/accounts-password.ts
- packages/password/src/accounts-password.ts
- packages/password/src/errors.ts
- packages/password/src/types/error-messages.ts
- packages/rest-express/__tests__/endpoints/password/register.ts
- packages/rest-express/src/endpoints/password/register.ts
- packages/server/__tests__/account-server.ts
- packages/server/src/accounts-server.ts
- packages/server/src/types/accounts-server-options.ts
Close #337 
- **Breaking change:** new server options `ambiguousErrorMessages` that default to true.
When this option is true all the messages that allow user enumeration are hidden:
- when trying to login with wrong credentials before was throwing with `User not found`, now `Invalid credentials`
- when trying to send an email to reset the password if the user email is not found fail silently
- when trying to send an email to verify the password if the user email is not found fail silently
- when trying to create a new user, we return null to the client instead of the user id (the transports are intercepting the id and return null) if user already exist the function will fail silently
- when trying to impersonate, we return `{ authorized: false }`
- **Breaking change:** the register route …
> User enumeration

- packages/boost/README.md
Replace AccountsServer with AccountsBoost in usage doc for boost README
contributes to accounts-js/accounts#368
as discussed here https://github.com/accounts-js/accounts/issues/368#issuecomment-443282080
> [doc](boost-usage): Replace AccountsServer with AccountsBoost

- packages/database-mongo/__tests__/database-tests.ts
- packages/database-mongo/__tests__/index.ts
- packages/database-mongo/package.json
- packages/database-mongo/src/mongo.ts
- packages/database-tests/tsconfig.json
- packages/graphql-api/src/modules/accounts/resolvers/user.ts
Closes #521 
@pradel This is a pretty simple fix, do you think is sufficient or should we always ensure that `user.id` is set even if mongo is being used?
> Try to use user._id or user.id

- package.json
- packages/e2e/__tests__/servers/server-graphql.ts
- packages/e2e/__tests__/servers/server-rest.ts
- packages/password/__tests__/accounts-password.ts
- packages/password/src/accounts-password.ts
- packages/password/src/errors.ts
- packages/password/src/types/error-messages.ts
- packages/server/__tests__/utils/__snapshots__/email.ts.snap
- packages/server/__tests__/utils/email.ts
- packages/server/src/types/email-templates-type.ts
- packages/server/src/utils/email.ts
- yarn.lock
Close #51 
**Breaking change** Enabled by default, if you don't want to send the email set the accounts-password `notifyUserAfterPasswordChanged` option to false.
> [password] Send user an email when their password has been changed

- packages/database-typeorm/package.json
- yarn.lock
Since it can be used with mysql etc we let the user choose
> Typeorm should not have pg in its dependencies

- package.json
- packages/graphql-client/src/graphql-client.ts
- yarn.lock
The problem we have currently is that we try catch around the mutate and query functions so we do not forward the graphql error object. The limitation I found is that I cannot access the `graphqlErrors` property when the function is throwing.
> [@accounts/graphql-client] Remove the try catch around the mutate and query functions to forward the native graphql error

- packages/password/src/accounts-password.ts
Looks like `minimumPasswordLength` is not used
> [@accounts-password] Remove the unused minimumPasswordLength option and improve the options description

- docs/databases/typeorm.md
- examples/README.md
- examples/accounts-boost/README.md
- website/sidebars.json
I added a typeorm.md file copying from the mongo one.
Also listed both accounts-boost and the typeorm-postgres example on the examples/README.md
Fixed a typo on accounts-boost README with a double "two two" word. So meta, two times two. Hahaha
Close #682
> Adding TypeORM to docs

- packages/client-password/__tests__/client-password.ts
- packages/client-password/package.json
- packages/client-password/src/client-password.ts
- website/docs/strategies/password-client.md
- website/docs/strategies/password.md
- website/sidebars.js
- yarn.lock
We decided to remove the client side hashing of the password by default. It does not provide more security if you use https, and is leading to some confusion.
In order to migrate to not break the login and registering of your existing user you will need to follow this migration:
First you will need to install the `crypto-js` npm library:
```
yarn add crypto-js
npm install crypto-js --save
```
Then setup the `hashPassword` option:
```javascript
import { SHA256 } from 'crypto-js';
import { AccountsClient } from '@accounts/client';
import { AccountsClientPassword } from '@accounts/client-password';
const accountsClient = new AccountsClient({});
const accountsPassword = new AccountsClientPassword(accountsClient, {
hashPassword: password => {
// Here we hash the password on the client before …
```
> [@accounts/client-password] Remove client side hashing of the password, create docs for `client-password`

- packages/database-mongo/__tests__/index.ts
- packages/database-mongo/src/mongo.ts
- packages/server/__tests__/account-server.ts
- packages/server/src/accounts-server.ts
- packages/server/src/types/accounts-server-options.ts
- packages/server/src/types/token-creator.ts
- packages/types/src/types/database-interface.ts
Hi,
In our project, we use a 3rd party authenticator service. This service manages access tokens itself. We wrote an `AuthenticationService` to support it, but it has duplicate code with `accounts-server` (and specific graphql endpoints) since we can't use its `loginWithService` and `refreshTokens` functionality.
The reason why we can't use `loginWithService` is the way we deliver our 3rd party token to the client. The only way for us to do that with `accountsjs` is to use it as a session token. then we create access token and refresh token using `accounts` and deliver them. since `accounts-server` generates the session token itself, `loginWithService` is not capable of supporting this scenario.
The way we thought of solving it, is to provide `accounts-server` with a custom `token …
> [discuss] accounts-server token creator

- packages/client/__tests__/accounts-client.ts
- packages/client/src/accounts-client.ts
add the ability to force refreshing the client tokens.
followup of #774.
@davidyaha
> add force refreshTokens to client

- packages/graphql-api/package.json
Currently hitting this https://github.com/ardatan/graphql-toolkit/issues/259 issue with the 0.5.12 version of graphql-toolkit. Upgrading in an attempt to solve https://github.com/accounts-js/accounts/issues/836
> graphql-toolkit version bump to 0.5.17 to fix `await` issue

- packages/graphql-client/src/graphql-client.ts
- packages/graphql-client/src/graphql/impersonate.mutation.ts
fixes an incorrect graphql query and also implements the user fields fragment that getUser uses
> Impersonation fixes

- examples/react-rest-typescript/src/Email.tsx
- packages/client-password/__tests__/client-password.ts
- packages/client-password/src/client-password.ts
- packages/client/src/transport-interface.ts
- packages/graphql-api/__tests__/modules/accounts-password/resolvers/mutation.ts
- packages/graphql-api/src/models.ts
- packages/graphql-api/src/modules/accounts-password/resolvers/mutation.ts
- packages/graphql-api/src/modules/accounts-password/schema/mutation.ts
- packages/graphql-client/src/graphql-client.ts
- packages/password/src/accounts-password.ts
- packages/rest-client/__tests__/rest-client.ts
- packages/rest-client/src/rest-client.ts
- packages/rest-express/__tests__/endpoints/password/add-email.ts
- packages/rest-express/src/endpoints/password/add-email.ts
- packages/rest-express/src/express-middleware.ts
Expose the accounts `addEmail` server function to be called directly from the client.
See screenshot of the example.
> [@accounts/password] Expose `addEmail` to the client

- examples/accounts-boost/src/monolithic/app-server.ts
- packages/boost/src/index.ts
- packages/server/__tests__/account-server.ts
- packages/server/src/accounts-server.ts
- packages/server/src/types/accounts-server-options.ts
- packages/server/src/utils/tokens.ts
Our project want to use RS256 in jwt signing, which use a pair of public / private key instead of a single string secret, and also we want to override `createTokens` function to add custom logic. So making the following changes in this pull request:
1. Allow `tokenSecret` to accept a pair of public / private key instead of a single string secret, and add two private function `getSecretOrPublicKey` and `getSecretOrPrivateKey` to get string secret or public / private key when sign or verify jwt.
2. ~~Make `createTokens` function become async, so when override `createTokens` function, async functions can be easily added.~~
> feat(server): allow tokenSecret to accept a pair of public / private key

- packages/express-session/src/index.ts
- packages/graphql-api/__tests__/modules/accounts/resolvers/mutation.ts
- packages/graphql-api/src/modules/accounts/resolvers/mutation.ts
- packages/rest-express/__tests__/endpoints/impersonate.ts
- packages/rest-express/__tests__/endpoints/refresh-access-token.ts
- packages/rest-express/src/endpoints/impersonate.ts
- packages/rest-express/src/endpoints/refresh-access-token.ts
- packages/server/__tests__/account-server.ts
- packages/server/src/accounts-server.ts
**This will be a breaking change for you only if you call these server functions directly in your code** if you just call these functions from the client you don't have to change anything.
```js
// Before
refreshTokens(accessToken: string, refreshToken: string, ip: string, userAgent: string)
// After
refreshTokens(accessToken: string, refreshToken: string, infos: ConnectionInformations)
```
```js
// Before
impersonate(accessToken: string, impersonated: object, ip: string, userAgent: string)
// After
impersonate(accessToken: string, impersonated: object, infos: ConnectionInformations)
```
> refactor(server)!: unify ConnectionInformations arguments

- packages/graphql-client/src/graphql/get-user.query.ts
Hey!
This change is for readability on graphql loggers and also for conditional apollo links that rely on operation names.
I would love to see this merged quickly as it does not break anything.
Thanks!
> chore(graphql-client): name the getUser mutation

- packages/client-password/__tests__/client-password.ts
- packages/client-password/src/client-password.ts
- packages/graphql-api/src/modules/accounts-password/resolvers/mutation.ts
- packages/password/src/accounts-password.ts
- packages/password/src/types/index.ts
- packages/password/src/types/password-create-user-type.ts
- packages/password/src/utils/encryption.ts
- packages/types/src/index.ts
- packages/types/src/types/services/password/create-user.ts
- packages/types/src/types/services/password/login-user.ts
- packages/types/src/types/services/password/password-type.ts
Close #818 #825 
- `PasswordCreateUserType` has been renamed to `CreateUserServicePassword` and is now exported from `@accounts/types`
- `PasswordLoginType` as been renamed to `LoginUserPasswordService` and is now exported from `@accounts/types`
- `PasswordType` is now exported from `@accounts/types`
> fix!: fix client password types

- packages/password/__tests__/utils/encryption.ts
- packages/password/src/accounts-password.ts
- packages/password/src/utils/encryption.ts
- packages/password/src/utils/index.ts
- packages/types/src/index.ts
- packages/types/src/types/hash-algorithm.ts
- yarn.lock
Close #811 
You can now customise the hashing and verification of the password.
By default we use bcrypt to hash the password. We now provide the following 2 options:
- `hashPassword?: (password: string) => Promise<string>;` 
- `verifyPassword?: (password: string, hash: string) => Promise<boolean>;`
If you want to use `argon2` for example you can do the following:
```js
const argon2 = require('argon2');
const passwordOptions = {
hashPassword: (password) => argon2.hash("password"),
verifyPassword: (password, hash) => argon2.verify(hash, password),
};
```
- remove the `passwordHashAlgorithm` option. You can have the same behavior as before by providing the new `hashPassword` option.
> feat(password)!: add custom password hashing option

- packages/password/src/accounts-password.ts
- packages/password/src/errors.ts
- packages/password/src/index.ts
- packages/server/src/index.ts
- packages/server/src/utils/accounts-error.ts
- website/docs/handling-errors.md
- website/sidebars.js
The idea is to throw some custom errors with a code attached to them. That way the user can whitelist all the possible errors and consider the other ones as internal server errors.
There are a few requirements:
- each public function should expose an enum containing all the possible errors
- all the errors should be documented
You can use them the following way:
```ts
import { AccountsJsError } from '@accounts/server';
import { CreateUserErrors } from '@accounts/password';
const run = async () => {
try {
await accountsPassword.createUser({
// ...
});
} catch (error) {
if (error instanceof AccountsJsError) {
// you can access the error message via `error.message`, eg: "Email already exists"
// you can access the code via `error.code`
// eg:
if (error.code === …
```
> feat(password): use custom error

- packages/rest-express/src/utils/send-error.ts
The rest express package will now return the code with the error message.
Example response:
```json
{"message":"Invalid credentials","code":"InvalidCredentials"}
```
> feat(rest-express): return the new error code

- packages/express-session/__tests__/accounts-session.ts
- packages/express-session/src/index.ts
- packages/server/src/accounts-server.ts
- packages/server/src/types/accounts-server-options.ts
- This might take up to 300ms, and if someone is using Accounts with express, it will run as part of the middleware.
Adding 300ms to something we don't really need the response of, is not needed.
- This PR also includes a fix for this issue: https://github.com/accounts-js/accounts/issues/933 
- Also, I pushed an optional fix for `express-session`. The `resolve` method there is not really mandatory, since we are running `renew`, which executes `refreshTokens` and eventually pulls `User` from the database, so we have the `user` already. So `resolve` could be optional!
> feat: add new `useInternalUserObjectSanitizer` option

- packages/database-manager/__tests__/database-manager.ts
- packages/database-manager/src/database-manager.ts
- packages/database-mongo/__tests__/index.ts
- packages/database-mongo/src/mongo.ts
- packages/database-typeorm/src/typeorm.ts
- packages/password/__tests__/__snapshots__/accounts-password.ts.snap
- packages/password/__tests__/accounts-password.ts
- packages/password/src/accounts-password.ts
- packages/types/src/types/services/password/database-interface.ts
Adding the method `removeAllPasswordResetTokens` to the `password`  package. This method is called within the `changePassword` method. It removes all password reset tokens from the user storage.
> feat(password): remove reset password tokens on change password

- packages/graphql-client/src/graphql-client.ts
- packages/graphql-client/src/graphql/add-email.mutation.ts
This PR:
- fixes the addEmail feature which was incorrectly linked to changePassword in the graphql-client package
- adds  the missing addEmail mutation.
- includes a `verified` parameter on the mutation to allow users to specify if the new email they're adding should be marked as verified.
- Updates the following packages to take account of the new mutation: `client`, `client-password`, `graphql-api` and `graphql-client`
- adds some missing types that were flagged whilst running the tests
> fix(graphql-client): fix add email mutation

- packages/graphql-client/package.json
- packages/graphql-client/src/GraphQLErrorList.ts
- packages/graphql-client/src/graphql-client.ts
closes: https://github.com/accounts-js/accounts/issues/938
> fix(graphql-client): reduce bundle size by importing only graphql subpackages

- packages/graphql-client/src/graphql-client.ts
- packages/graphql-client/src/graphql/create-user.mutation.ts
- packages/graphql-client/src/graphql/login-with-service.mutation.ts
completes what i did in https://github.com/accounts-js/accounts/pull/894
I forgot there about those who are using accounts accounts client with graphql transport 🙊(now we do). So graphql-client's `createUser` and `authenticate` mutations responses will also contain user data => it will be available when using accounts `client` and/or `client-password`
> feat(graphql-client): load user data after login/registration when using @accounts/graphql-client

- examples/graphql-server-typeorm-postgres/src/index.ts
- packages/password/src/accounts-password.ts
- packages/server/src/accounts-server.ts
- packages/server/src/types/accounts-server-options.ts
- packages/types/src/types/authentication-service.ts
- packages/types/src/types/database-interface.ts
- packages/types/src/types/services/password/database-interface.ts
The goal is to allow you to pass your custom user type when you call the accounts-js functions manually server side
that way you can do:
```ts
interface MyUser extends User {
firstName: string
}
const accountsServer = new AccountsServer<MyUser>({ ... }),
const user = await accountsServer.findUserById('id');
// user will now be of type `MyUser` instead of `User`
```
> feat: create User generic to allow better typechecking

- packages/database-mongo/src/mongo.ts
The following indexes where missing:
- reset password token
- verify email token
> feat(mongo): add missing indexes for the password service

- packages/oauth/package.json
I will open another PR for removing it specificallly from oauth-instagram package. should be easy to repalce like with twitter package using this.oauth instead!
This would partially fix #937
> chore(deps): remove dependency request-promise from packages/oauth

- packages/graphql-api/__tests__/modules/accounts-password/resolvers/mutation.ts
- packages/graphql-api/__tests__/modules/accounts/resolvers/mutation.ts
- packages/graphql-api/src/modules/accounts-password/resolvers/mutation.ts
- packages/graphql-api/src/modules/accounts/index.ts
- packages/graphql-api/src/modules/accounts/resolvers/mutation.ts
- packages/graphql-api/src/utils/context-builder.ts
- packages/types/src/types/connection-informations.ts
The goal of this pr is to provide a way for the user to extends the info object that will be passed down to the server functions from the GraphQL context.
I will create another pr adding this for REST too.
> feat(graphql-api): ability to extend connection information

- packages/client/src/transport-interface.ts
- packages/graphql-api/__tests__/modules/accounts/resolvers/mutation.ts
- packages/graphql-api/src/models.ts
- packages/graphql-api/src/modules/accounts/resolvers/mutation.ts
- packages/graphql-api/src/modules/accounts/schema/mutation.ts
- packages/graphql-api/src/modules/accounts/schema/types.ts
- packages/rest-client/__tests__/rest-client.ts
- packages/rest-client/src/rest-client.ts
- packages/rest-express/src/endpoints/impersonate.ts
- packages/server/src/accounts-server.ts
- packages/types/src/types/impersonation-result.ts
Close #827
- `graphql-api`: changed the types of the `impersonate` mutation to allow to impersonation via `userId` and `email`
> fix!: fix impersonate transports params

- packages/database-typeorm/src/entity/UserSession.ts
This attempts to address the following issue when running the example repo for postgres + GraphQL (Close https://github.com/accounts-js/accounts/issues/991).
TypeORM has difficulty inferring underlying types from nullable types and will cast something like `string | null` into `object`. This PR adds an explicit type to typeORM's decorator.
> fix(typeorm): add explicit types to userSession and IP decorator

- website/docs/getting-started.md
You where calling `.listen` on the promise.
other option would've been `await (await accountsBoost(...)).listen`,
but I figured that could be a bit confusing.
> docs: fix missing await in getting started

- website/docs/server.md
- website/docs/strategies/password-client.md
the users your documentation refers to are not all people that would be referred to as 'him'. using gender neutral language is welcoming to more potential users of AccountsJS
> docs: use gender neutral language in documentation

- packages/graphql-api/__tests__/modules/accounts-password/resolvers/mutation.ts
- packages/graphql-api/package.json
- packages/graphql-api/src/modules/accounts-password/resolvers/mutation.ts
- packages/password/src/accounts-password.ts
- packages/rest-express/__tests__/endpoints/password/verify-email.ts
- packages/rest-express/package.json
- packages/rest-express/src/endpoints/password/verify-email.ts
- yarn.lock
BREAKING CHANGE: calling `password.sendVerificationEmail ` will not hide the error anymore if the user is not found when `ambiguousErrorMessages` is true, this error will now be hidden by the transport layer (rest-express, graphql).
**Only a breaking change if** you expose `password. sendVerificationEmail ` to your users without using the one of the transport layers.
This change is made to make the service a bit more "dumb" and to allow to call this function server side and get the error in case the user is not found.
> chore(password)!: move `sendVerificationEmail` user check to transport 

- packages/graphql-api/__tests__/modules/accounts-password/resolvers/mutation.ts
- packages/graphql-api/src/modules/accounts-password/resolvers/mutation.ts
- packages/password/src/accounts-password.ts
- packages/rest-express/__tests__/endpoints/password/reset.ts
- packages/rest-express/src/endpoints/password/reset.ts
BREAKING CHANGE: calling `password.sendResetPasswordEmail` will not hide the error anymore if the user is not found when `ambiguousErrorMessages` is true, this error will now be hidden by the transport layer (rest-express, graphql).
**Only a breaking change if** you expose `password.sendResetPasswordEmail` to your users without using the one of the transport layers.
This change is made to make the service a bit more "dumb" and to allow to call this function server side and get the error in case the user is not found.
> chore(password)!: move `sendResetPasswordEmail` user check to transport

- packages/database-manager/__tests__/database-manager.ts
- packages/database-manager/src/database-manager.ts
- packages/database-mongo-password/src/mongo-password.ts
- packages/database-mongo/__tests__/index.ts
- packages/database-mongo/src/mongo.ts
- packages/database-typeorm/src/typeorm.ts
- packages/oauth/__tests__/accounts-oauth.ts
- packages/password/__tests__/accounts-password.ts
- packages/password/package.json
- packages/password/src/accounts-password.ts
- packages/types/src/types/services/password/database-interface.ts
- yarn.lock
BREAKING CHANGE: `db.setResetPassword` has been removed from the database interface as it was just an alias to `db.setPassword`.
If you are using this method, use `setPassword` instead.
Note: if you are using the typeorm adapter, you also need to call `db.removeAllResetPasswordTokens` to keep the same behavior as before.
> chore!: remove the database `setResetPassword` method

- examples/graphql-server-typeorm-postgres/README.md
Hi there! Just fixing a markdown typo in the examples readme.
> fix(example-typeorm): fix readme link

- packages/password/package.json
I'm currently seeing 
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: level-up-tutorials@3.0.0
npm ERR! Found: @accounts/server@0.30.0
npm ERR! node_modules/@accounts/server
npm ERR!   @accounts/server@"^0.30.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @accounts/server@"^0.19.0" from @accounts/password@0.30.0
npm ERR! node_modules/@accounts/password
npm ERR!   @accounts/password@"^0.30.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/scotttolinski/.npm/eresolve-report.txt for a …
```
> fix(password): update peer dependencies

- packages/graphql-api/src/utils/authenticated-resolver.ts
I'm using it with nexus.js.org and it would break the types because it says 'any' for all of them.
> feat(graphql-api): custom typings for authenticated-resolver

- packages/graphql-api/package.json
`graphql` is a peer dependency of `@graphql-tools/utils` and needed at runtime.
> fix(graphql-api): add graphql to peerDependencies

- packages/client/src/accounts-client.ts
The session created when impersonating another user is is not
invalidated when the client stops impersonation. This PR adds a call to
logout to properly invalidate the session before restoring the original
tokens from storage.
Fixes: #1096
> fix(client): invalidate session when stopping impersonation

- packages/server/__tests__/account-server.ts
- packages/server/src/accounts-server.ts
The access token received after an impersonation is wrongly encoded with
the session id instead of the session token. This causes all subsequent
session operations with the new token to fail.
This PR fixes this bug and has the tests updated as well to reflect
this change.
Fixes: #1094
> fix(server): fix impersonation token

- packages/apollo-link-accounts/tsconfig.json
- packages/client-password/tsconfig.json
- packages/client/tsconfig.json
- packages/graphql-client/tsconfig.json
- packages/rest-client/tsconfig.json
- tsconfig.json
BREAKING CHANGE: Drop support for node 8. Minimum node version is node 10.
Closes #1091
> fix!: change target to es2018 for server packages

- packages/password/src/accounts-password.ts
BREAKING CHANGE: The createUser function now await `sendVerificationEmail` only if `sendVerificationEmailAfterSignup` is true. This change was made to be able to run this function in lambda.
> chore(password)!: await sendVerificationEmail during user signup

- packages/database-mongo-password/package.json
- packages/database-mongo-sessions/package.json
Both `database-mongo-sessions` and `database-mongo-password` have a dependency on `mongodb`, which is not in their `package.json` files:
https://github.com/accounts-js/accounts/blob/7680a41c422104038dd69d62ce80381a113c5c61/packages/database-mongo-sessions/src/utils.ts#L1-L5
https://github.com/accounts-js/accounts/blob/7680a41c422104038dd69d62ce80381a113c5c61/packages/database-mongo-password/src/utils.ts#L1-L5
This PR adds `mongodb` as a peer dependency for both of these packages.
> fix(mongo-session/password): added missing mongodb peer dependency

- packages/server/__tests__/account-server.ts
- packages/server/src/accounts-server.ts
- packages/server/src/types/accounts-server-options.ts
- packages/server/src/types/user-object-sanitizer-function.ts
BREAKING CHANGE: Change the option `userObjectSanitizer` parameters. `pick` and `omit` are removed, if you are relying on them, you can import them from lodash directly.
> chore(server)!: simplify userObjectSanitizer option

- packages/database-mongo-password/package.json
- packages/database-mongo-sessions/package.json
- packages/database-mongo/package.json
- yarn.lock
The `@accounts/mongo` package types depend on the `mongodb` types. Doesn't work with Yarn 2 PnP at the moment.
> fix(mongo): put mongodb types in dependencies

- packages/graphql-api/package.json
- packages/password/package.json
The `peerDependencies` were a little outdated. Since the version is still 0...., the `^` is behaving like a `~`. So while installing, the install was not working because of broken dependency tree.
> chore: Update peer dependencies to the latest version

- .changeset/silly-poems-mix.md
- packages/graphql-api/src/modules/accounts/index.ts
- packages/graphql-api/src/utils/context-builder.ts
> fix: fix graphql api error with apollo subscriptions

- examples/accounts-boost/package.json
- examples/accounts-boost/src/microservice/app-server.ts
- yarn.lock
I was checking the examples after porting them to graphql-modules v1 and I've noticed that some of them were broken... since a long time. I've fixed the accounts-boost microservice example to work with graphql-tools 6+.
> fix: broken accounts-boost examples since graphql-tools 6+

- .changeset/eighty-zoos-glow.md
- packages/graphql-api/package.json
Currently when you go to the page on NPM for this package it points to the old archived version which is confusing when the code actually lives here
> fix: repo links in graphql-api package.json

- .changeset/slimy-pugs-refuse.md
- packages/graphql-api/README.md
- website/docs/transports/graphql.md
Within the last month I discovered this project and started implementing it in my own. I found the docs to be a little on the lean side, so I thought I would contribute to them.
I added an example of how to authenticate with a service using GraphQL. I used most of the information [from this code](https://github.com/accounts-js/accounts/blob/220566425755a7015569d8e518095701ff7122e2/packages/graphql-api/src/modules/accounts/schema/types.ts). I was not sure of the "official" `serviceName` for each one of them though. 
I would also like to add additional information for each of the services, but am not sure what content to write, or if it should be organized differently. So this is my _first draft_ so to say. Please offer any feedback that would be helpful to fill out these docs a little …
> docs: Update to GraphQL API Documentation

- .changeset/fifty-pans-smash.md
- packages/database-mongo-password/src/mongo-password.ts
I know some issues were addressed in #1180.  These are a couple of other issues that arise because in this version of the driver, the result of updateOne() and updateMany() is now different.  Keeping previous check in there for backwards compatibility.
> fix: patch for issue in mongo driver 4.x.x

- .changeset/rotten-rules-repair.md
- .changeset/swift-panthers-play.md
- packages/database-mongo-sessions/__tests__/mongo-sessions.ts
- packages/database-mongo-sessions/src/mongo-sessions.ts
- packages/database-mongo/__tests__/database-tests.ts
- packages/database-mongo/__tests__/index.ts
- packages/database-mongo/src/types/index.ts
This fix is related to this bug report: https://github.com/accounts-js/accounts/issues/1204
The configuration option of `convertSessionIdToMongoObjectId` was not being checked when using the `idProvider` to create a new session.
> fix: check `convertSessionIdToMongoObjectId` before using `idProvider`

- .changeset/perfect-cobras-shop.md
- packages/database-mongo-password/src/mongo-password.ts
> fix: mongodb 5 compatability in all mongo password methods
