accounts-js/accounts

circle.yml
Setup circleci to use yarn https://circleci.com/docs/install-and-use-yarn/
=> Circleci yarn

src/client/AccountsClient.js, src/common/AccountsCommon.js, src/common/UserObjectType.js, src/server/AccountsServer.js, src/server/AccountsServer.spec.js, src/server/DBDriver.js
This PR introduces the Accounts.createUser function, tests, and beginnings of the DBDriverInterface, and a variety of minor fixes.
=> Server side Accounts.createUser

packages/server/src/DBInterface.js
Flow conditional return for `findSessionById`
=> Flow conditional return

package.json, packages/server/src/AccountsServer.js, packages/server/src/AccountsServer.spec.js, yarn.lock
It look like I remove this one on #49 sorry!
I updated the test, now it will fail if the check is missing.
=> Config need to throw when no db object is passed

packages/server/src/AccountsServer.js, packages/server/src/DBInterface.js, packages/server/src/emailTemplates.js
Add sendEnrollmentEmail function
=> sendEnrollmentEmail

packages/client/src/AccountsClient.js, packages/client/src/config.js, packages/client/src/index.js
Allow users to supply their own storage. Mainly for react-native users that uses [AsyncStorage](http://facebook.github.io/react-native/releases/0.41/docs/asyncstorage.html#asyncstorage) which is a superset of the borwser's `localStorage`
=> Set token storage

.gitignore, packages/client/package.json, packages/client/src/AccountsClient.js, packages/client/webpack.config.js, packages/common/package.json, packages/common/webpack.config.js, packages/server/package.json, packages/server/webpack.config.js, packages/server/yarn.lock
Also, added loginWithPassword result to callback and as return value
=> chore(build): added support for UMD build along with ES6 build

packages/server/src/AccountsServer.js, packages/server/src/config.js, packages/server/src/email.js
LMK if you want to add the emailjs config types as well
=> Improved email configuration typings

packages/server/src/AccountsServer.js, packages/server/src/AccountsServer.spec.js, packages/server/src/config.js
Added the ability to create a completely custom email flow
=> Custom email handling

package.json, packages/client/package.json, packages/client/src/AccountsClient.js, packages/client/src/AccountsClient.spec.js, packages/client/src/TransportInterface.js, packages/client/src/encryption.js, packages/common/package.json, packages/common/src/index.js, packages/common/src/types.js, packages/server/package.json, packages/server/src/AccountsServer.js, packages/server/src/AccountsServer.spec.js, packages/server/src/config.js, packages/server/src/encryption.js, packages/server/yarn.lock, yarn.lock
Wow, for some reason I missed the fact that this branch was not merged.
I will greatly appreciate a quick CR.
=> Fix reset password

packages/server/src/AccountsServer.js
After long, and hard thought (not really), that seems like the first step to modular authentication strategy. It also allows for any consuming code to have it's own auth process and setup a session for a given user.
=> Added loginWithUser to allow for any auth support

res/notes/modular-auth.md
I had a hard time making sense out of things without getting it all written.
Would love to hear feedback on my assumptions and maybe things I did not understand correctly.
The notes might be a little messy but I tried to format it in some way. Hope it's understandable.
=> Added my modular authorization notes

packages/server/src/accounts-server.ts, packages/server/src/config.ts
Found out we were missing this part.
I think the docs now are more accurate: http://accounts-js.netlify.com/docs/emails/ 😄
=> Add configurable email templates

packages/client/__tests__/accounts-client.ts, packages/client/src/accounts-client.ts, packages/client/src/transport-interface.ts, packages/common/src/types.ts, packages/oauth/src/accounts-oauth.ts, packages/password/package.json, packages/server/yarn.lock
Not all tests are fixed yet but this is working with the current rest-client.
Please wait/fix tests before merging
=> Getting the client to work with password first

packages/client/__tests__/accounts-client.ts, packages/client/src/accounts-client.ts, packages/client/src/module.ts
Since we don't store the user we can now remove this dead code
=> remove unused actions to store user

packages/client/__tests__/accounts-client.ts, packages/client/src/accounts-client.ts
=> refresh session check accessToken still valid first in order to not refresh the session each time

packages/database-mongo/package.json, packages/oauth/package.json, packages/server/package.json, packages/two-factor/package.json, tsconfig.json
We need this fix for typescript users
=> @accounts/types should be a dependency not dev dependency

packages/rest-express/__tests__/endpoints/oauth/provider-callback.ts, packages/rest-express/src/endpoints/oauth/provider-callback.ts, packages/rest-express/src/express-middleware.ts, packages/rest-express/src/types.ts
=> Add OAuth callbacks

packages/oauth/src/accounts-oauth.ts, packages/server/src/accounts-server.ts
OAuth user creation did not trigger the user creation hook, now it does :)
=> Trigger the correct hooks when using oauth

packages/password/__tests__/accounts-password.ts, packages/password/src/accounts-password.ts, packages/rest-client/__tests__/rest-client.ts, packages/rest-client/package.json, packages/rest-client/src/rest-client.ts, packages/rest-express/__tests__/endpoints/password/change-password.ts, packages/rest-express/package.json, packages/rest-express/src/endpoints/password/change-password.ts, packages/rest-express/src/express-middleware.ts
The change password function can be used only when the user is logged in.
=> Create a changePassword function

packages/password/src/accounts-password.ts, packages/two-factor/package.json, packages/two-factor/src/index.ts, packages/two-factor/src/two-factor.ts, packages/two-factor/src/types/index.ts, packages/two-factor/src/types/options.ts, packages/two-factor/src/types/two-factor-service.ts, packages/two-factor/src/utils/index.ts, packages/two-factor/src/utils/user.ts
- create a types folder to align to the rest of the code
- create a `getUserTwoFactorService` utils that can be used to check if the user have two factor enabled or not
=> create a types folder

packages/oauth/__tests__/accounts-oauth.ts, packages/oauth/src/accounts-oauth.ts
=> No longer set profile data in OAuth

package.json, yarn.lock
Now when we commit a hook will be run and our updated files will be prettied 🎉
=> Add prettier commit hook

packages/client-password/src/client-password.ts
return tokens used by loginWithService so they can be used by the calling function.
=> return tokens from loginWithService

packages/rest-client/src/rest-client.ts, packages/rest-express/__tests__/endpoints/impersonate.ts, packages/rest-express/src/endpoints/impersonate.ts
=> Fix rest-express impersonate call

packages/graphql-api/README.md, packages/graphql-api/package.json, packages/graphql-api/src/graphql/types.ts, packages/graphql-api/src/resolvers/user.ts, packages/graphql-api/src/schema-builder.ts, packages/graphql-api/src/types/graphql.ts, packages/graphql-api/src/utils/context-builder.ts, packages/graphql-client/src/graphql-client.ts
related to #362 
- remove the `email` key on the `User` object
- remove the `CreateUserProfileInput` type and add docs
- `EmailRecord` record object can't be empty
=> graphql remove the `email` key on the user and the `CreateUserProfileInput` type

packages/graphql-api/src/graphql/mutations.ts, packages/graphql-api/src/graphql/queries.ts, packages/graphql-api/src/graphql/types.ts, packages/graphql-api/src/resolvers/change-password.ts, packages/graphql-api/src/resolvers/register-user.ts, packages/graphql-api/src/resolvers/reset-password.ts, packages/graphql-api/src/resolvers/send-reset-password-email.ts, packages/graphql-api/src/resolvers/two-factor.ts, packages/graphql-api/src/resolvers/verify-email.ts, packages/graphql-api/src/schema-builder.ts, packages/graphql-api/src/scripts/schema-to-types.ts, packages/server/src/accounts-server.ts
=> [graphql-api] build resolvers and schema based on the service

packages/apollo-link-accounts/.npmignore, packages/apollo-link-accounts/package.json, packages/apollo-link-accounts/src/index.ts, packages/apollo-link-accounts/tsconfig.json, yarn.lock
=> New package: @accounts/apollo-link

packages/apollo-link-accounts/README.md, packages/client-password/README.md, packages/client/README.md, packages/database-mongo/README.md, packages/database-redis/README.md, packages/express-session/README.md, packages/graphql-client/README.md, packages/graphql-client/src/index.ts, packages/password/README.md, packages/rest-client/README.md, packages/rest-express/README.md, packages/server/README.md, packages/types/readme.md
- @accounts/apollo-link
- @accounts/client-password
- @accounts/client
- @accounts/server
- @accounts/password
- @accounts/graphql-client
=> Add some README to the packages for npm

packages/apollo-link-accounts/package.json, packages/client/package.json, packages/database-manager/package.json, packages/database-mongo/package.json, packages/database-redis/package.json, packages/database-tests/package.json, packages/express-session/package.json, packages/graphql-api/package.json, packages/graphql-client/package.json, packages/oauth-instagram/package.json, packages/oauth-twitter/package.json, packages/oauth/package.json, packages/password/package.json, packages/rest-client/package.json, packages/rest-express/package.json, packages/server/package.json, packages/two-factor/package.json
=> add start script to all packages

packages/graphql-api/package.json
=> Add graphql-tools as a peer dep of graphql-api

packages/client-password/__tests__/client-password.ts, packages/client-password/src/client-password.ts
Currently the change password function does not work
=> Also encrypt the old password when trying to change it

README.md, package.json
Organized readme some as well, mainly pointing people at the docs site. Feel free to edit
=> Improve contributing documentation, fixes #390

packages/e2e/__tests__/databases/index.ts, packages/e2e/__tests__/databases/mongo.ts, packages/e2e/__tests__/password.ts, packages/e2e/__tests__/servers/index.ts, packages/e2e/__tests__/servers/server-graphql.ts, packages/e2e/__tests__/servers/server-rest.ts, packages/e2e/__tests__/servers/server.ts, packages/e2e/package.json, packages/e2e/tsconfig.json, packages/rest-express/__tests__/endpoints/password/change-password.ts, packages/rest-express/__tests__/endpoints/password/reset.ts, packages/rest-express/__tests__/endpoints/password/verify-email.ts, packages/rest-express/src/endpoints/password/change-password.ts, packages/rest-express/src/endpoints/password/reset.ts, packages/rest-express/src/endpoints/password/verify-email.ts, yarn.lock
The goal of this pr is to implement e2e for the suite. I am trying an approach that will allow us to write generic tests that should work no matter which database or transport is used.
I am using the accounts client in order to do the requests.
Any feedback welcome 🙌
=> Setup e2e testing

packages/e2e/__tests__/databases/index.ts, packages/e2e/__tests__/databases/mongo.ts, packages/e2e/__tests__/password.ts, packages/e2e/__tests__/servers/index.ts, packages/e2e/__tests__/servers/server-graphql.ts, packages/e2e/__tests__/servers/server-rest.ts, packages/e2e/package.json, packages/e2e/tsconfig.json, packages/rest-express/__tests__/endpoints/password/change-password.ts, packages/rest-express/__tests__/endpoints/password/reset.ts, packages/rest-express/__tests__/endpoints/password/verify-email.ts, packages/rest-express/src/endpoints/password/change-password.ts, packages/rest-express/src/endpoints/password/reset.ts, packages/rest-express/src/endpoints/password/verify-email.ts
See https://github.com/accounts-js/accounts/pull/384
=> Resend e2e testing pr

packages/password/src/accounts-password.ts
Mirrors oauth:
https://github.com/accounts-js/accounts/blob/57e1f6f4ce763a2a6534cbde3a9774b7c788d030/packages/oauth/src/accounts-oauth.ts#L38-L54
Defers to improve return speed
=> Emit events when creating password users

packages/password/__tests__/__snapshots__/accounts-password.ts.snap, packages/password/__tests__/accounts-password.ts, packages/password/src/accounts-password.ts
Check the arguments for the methods that are exposed to the client.
=> [@accounts/password] Check the arguments in the exposed methods

examples/graphql-server-typescript/package.json, examples/graphql-server-typescript/src/index.ts, examples/graphql-server-typescript/yarn.lock, examples/react-graphql-typescript/package.json, examples/react-graphql-typescript/src/Home.tsx, examples/react-graphql-typescript/yarn.lock
Had some issues with implementing the graphql packages into a new project.
Decided to try it out on the examples and had to upgrade the dependencies here.
Everything seems to be working so the issue must be on my side.
Been out for quite a while now so it's good to see that the project is thriving!
=> Updated graphql examples to latest accounts packages

docs/transports/graphql.md, packages/e2e/__tests__/password.ts, packages/password/src/accounts-password.ts
=> Enumerate user hide incorrectPassword message

packages/client-password/src/client-password.ts, packages/client/src/transport-interface.ts, packages/graphql-client/src/graphql-client.ts, packages/password/src/accounts-password.ts, packages/rest-client/src/rest-client.ts
Fix the types introduced by pr #505 :)
=> Fix the resetPassword types

packages/database-typeorm/README.md, packages/database-typeorm/src/entity/User.ts, packages/database-typeorm/src/typeorm.ts, packages/database-typeorm/src/types/index.ts
=> typeorm: fix email lookup

packages/password/__tests__/accounts-password.ts, packages/password/src/accounts-password.ts
=> sendVerificationEmail: Do not send an email if the address is already verified

packages/server/src/accounts-server.ts, packages/types/src/types/database-interface.ts
A create function cannot return null.
=> Fix create session type

examples/graphql-server-typescript/package.json, examples/graphql-server-typescript/yarn.lock, packages/database-manager/__tests__/database-manager.ts, packages/database-manager/src/database-manager.ts, packages/database-mongo/__tests__/index.ts, packages/database-mongo/src/mongo.ts, packages/database-mongo/src/types/index.ts, packages/database-typeorm/__tests__/index.ts, packages/database-typeorm/src/entity/User.ts, packages/database-typeorm/src/typeorm.ts, packages/oauth/__tests__/accounts-oauth.ts, packages/oauth/src/types/oauth-user.ts, packages/server/__tests__/account-server.ts, packages/server/src/accounts-server.ts, packages/types/src/types/database-interface.ts, packages/types/src/types/user.ts, res/notes/modular-auth.md
We now have the option to extend the user object, so it's time to remove the profile key on the user.
See https://github.com/accounts-js/accounts/issues/394
Close #616 #614
=> Remove user profile

examples/graphql-server-typescript/README.md
=> Fix graphql server example README

.circleci/config.yml, package.json, packages/boost/package.json, packages/client-password/package.json, packages/client/package.json, packages/client/src/accounts-client.ts, packages/database-manager/package.json, packages/database-mongo/package.json, packages/database-redis/package.json, packages/database-tests/package.json, packages/database-typeorm/package.json, packages/e2e/package.json, packages/error/package.json, packages/express-session/package.json, packages/graphql-api/__tests__/utils/context-builder.ts, packages/graphql-api/package.json, packages/graphql-client/package.json, packages/oauth-instagram/package.json, packages/oauth-twitter/package.json, packages/oauth/__tests__/accounts-oauth.ts, packages/oauth/package.json, packages/password/__tests__/accounts-password.ts, packages/password/package.json, packages/rest-client/package.json, packages/rest-express/package.json, packages/server/__tests__/account-server.ts, packages/server/package.json, packages/two-factor/package.json, packages/types/package.json, yarn.lock
- Upgrade jest to version 24
- Update other deps
=> Upgrade jest to version 24

packages/password/src/accounts-password.ts
Add description to the `validateUsername` option.
=> [@accounts/password] Add description to the `validateUsername` option

packages/password/__tests__/__snapshots__/accounts-password.ts.snap, packages/password/__tests__/accounts-password.ts, packages/password/src/accounts-password.ts
Call `validatePassword` options when `changePassword` is executed.
=> [@accounts/passowrd] Call `validatePassword` options when `changePassword` is executed

website/docs/strategies/password.md
Preview of the changed file https://deploy-preview-749--accounts-js.netlify.com/docs/strategies/password
=> Improve password strategy docs

website/docs/transports/graphql.md
=> Fix `@accounts/apollo-link` documentation

packages/password/__tests__/__snapshots__/accounts-password.ts.snap, packages/password/__tests__/accounts-password.ts, packages/password/src/accounts-password.ts
`invalidateAllSessionsAfterPasswordReset` and `invalidateAllSessionsAfterPasswordChanged` options
=> [@accounts/password] Add `invalidateAllSessionsAfterPasswordReset` and `invalidateAllSessionsAfterPasswordChanged` options

.circleci/config.yml, CONTRIBUTING.md, docker-compose.yml, examples/react-graphql-typescript/package.json, examples/react-rest-typescript/package.json, packages/database-redis/__tests__/database-tests.ts, packages/database-typeorm/__tests__/database-tests.ts, packages/e2e/__tests__/databases/typeorm.ts
To make testing changes easier locally, added docker compose file using the circleci images for the services.
=> chore: 🤖 Added docker-compose.yml for running tests locally

packages/client/src/token-storage-local.ts, packages/client/src/types/token-storage.ts
Close #807
Code extracted from https://github.com/accounts-js/accounts/pull/804
=> Update TokenStorage to support non async storage

website/docs/getting-started.md
Changes taken from file examples/accounts-boost/src/microservice/app-server.ts
See my despair as an accounts-js newcomer in #814
=> Update the documentation from the corresponding microservice example

packages/server/src/utils/email.ts, website/docs/email.md
=> Add a link in the console pointing to the email documentation if emails are not setup

packages/password/src/utils/encryption.ts
=> fix: avoid deprecation warnings by explicitly importing createHash

CONTRIBUTING.md, examples/README.md, examples/graphql-server-typeorm-postgres/README.md, examples/graphql-server-typescript/README.md, examples/react-graphql-typescript/README.md, examples/react-rest-typescript/README.md, examples/rest-express-typescript/README.md
=> docs: update example documentation

packages/apollo-link-accounts/src/index.ts
=> fix(apollo-link): fix infinite loop while refreshing the session

packages/graphql-client/src/graphql-client.ts
=> fix(graphql-client): fix empty Authorization header for Hasura

packages/server/__tests__/account-server.ts, packages/server/src/accounts-server.ts, packages/server/src/errors.ts, packages/server/src/index.ts, packages/server/src/utils/accounts-error.ts
Following the password pull request
=> feat(server): use custom error

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/1.Bug_report.md, .github/ISSUE_TEMPLATE/2.Feature_request.md, .github/ISSUE_TEMPLATE/config.yml
I took the next.js templates which are great and changed the wording for accounts-js :)
=> chore: add github issue template

examples/react-graphql-typescript/src/Home.tsx
This change in query fixes the Home page in the example to use getUser query now. Works up to 0.25.1 for me.
=> fix: update me -> getUser in examples/react-graphql-typescript

packages/database-mongo/__tests__/index.ts, packages/database-mongo/src/mongo.ts, packages/database-redis/src/redis.ts, packages/database-tests/src/index.ts, packages/database-typeorm/src/typeorm.ts, packages/types/src/types/session/database-interface.ts
PR adds new optional parameter to invalidateAllSessions method to allow not destroy all session on specific cases. (Such as invalidate all sessions except active one)
=> feature: add exclusion list to invalidateAllSessions method

examples/react-graphql-typescript/src/Signup.tsx
The client is otherwise broken
=> fix(example): workaround event pooling for react-graphql

examples/graphql-server-typeorm-postgres/.env, examples/graphql-server-typeorm-postgres/README.md, examples/graphql-server-typeorm-postgres/docker-compose.yml, examples/graphql-server-typeorm-postgres/package.json, examples/graphql-server-typeorm-postgres/src/index.ts, yarn.lock
Make typeorm server working out of the box
=> fix: typeorm example fixes

packages/apollo-link-accounts/README.md, packages/client-password/README.md, packages/client/README.md, packages/database-manager/README.md, packages/graphql-client/README.md, packages/rest-client/README.md, packages/rest-express/README.md, packages/server/README.md, packages/types/README.md, packages/types/readme.md
=> docs: normalise the packages README

packages/database-manager/__tests__/database-manager.ts, packages/database-manager/src/database-manager.ts, packages/database-mongo/__tests__/index.ts, packages/database-mongo/src/mongo.ts, packages/database-typeorm/src/typeorm.ts, packages/types/src/index.ts, packages/types/src/types/database-interface.ts, packages/types/src/types/mfa/authenticator.ts, packages/types/src/types/mfa/create-authenticator.ts, packages/types/src/types/mfa/create-mfa-challenge.ts, packages/types/src/types/mfa/database-interface.ts, packages/types/src/types/mfa/mfa-challenge.ts
- Create database types for mfa
- Mock mongo
- Mock typeorm
=> feat(types): create database mfa types

examples/rest-express-typescript/src/index.ts
=> fix(rest-example): fix mongo usage

packages/graphql-api/README.md
authenticated was just working with the proposed changes
=> docs: fix an issue in an example of the README for graphql-api

packages/database-mongo/package.json, packages/database-mongo/src/mongo.ts, packages/types/src/types/user.ts, yarn.lock
Reduce install size of `@accounts/mongo`.
=> chore(mongo): remove lodash from the dependencies

packages/password/src/accounts-password.ts, packages/server/src/accounts-server.ts
closes https://github.com/accounts-js/accounts/issues/1062
=> feat!: execute server hooks with await

packages/graphql-client/package.json
=> feat(graphql-client): support graphql ^15.0.0

packages/graphql-api/package.json
=> fix(graphql-api): update peer dependencies

website/docs/strategies/oauth.md
As discussed here: https://github.com/accounts-js/accounts/issues/875#issuecomment-643745781
Issues: #875 and #1031
=> docs: Add basic OAuth client docs

packages/database-typeorm/__tests__/typeorm-password.ts, packages/database-typeorm/__tests__/typeorm-sessions.ts, packages/database-typeorm/package.json
Copied over relevant tests from mongodb to typeorm.
=> test(typeorm): Add tests for typeorm

packages/database-typeorm/__tests__/typeorm-password.ts, packages/database-typeorm/src/typeorm.ts
This fixes the find query in `findUserByServiceId`
Fixes: #1108
=> fix(typeorm): fix query in findUserByServiceId #1108

packages/express-session/package.json, packages/graphql-api/package.json, packages/password/package.json, packages/rest-client/package.json, packages/rest-express/package.json
This PR updates the dependencies so that they would be up to date with the next release.
=> chore: updating peer dependencies to latest version

website/docs/databases/typeorm.md
=> docs: fix typo in TypeORM docs

.changeset/bright-snakes-grin.md, packages/server/src/types/accounts-server-options.ts
=> feat: allow partial emailTemplates option

tsconfig.json
=> feat: typescript target 2019

.changeset/lemon-dots-bake.md, packages/types/src/types/session/session.ts
closes https://github.com/accounts-js/accounts/issues/1197
=> fix(types-session): add missing extra data property

website/docs/client.md, website/docs/server.md
* how to restrict impersonation to specific users via `impersonationAuthorize`
* how to check if a networkSession is impersonated
---
Related to discussion https://github.com/accounts-js/accounts/discussions/1195
=> docs(server): add impersonation docs

modules/module-password/__tests__/resolvers/mutation.ts, modules/module-password/src/resolvers/mutation.ts, modules/module-password/src/schema/types.ts, packages/e2e/__tests__/password.ts, packages/password/__tests__/accounts-password.ts, packages/password/src/accounts-password.ts, packages/password/src/errors.ts, packages/password/src/types/error-messages.ts, packages/rest-express/__tests__/endpoints/password/register.ts, packages/rest-express/src/endpoints/password/register.ts, packages/server/__tests__/account-server.ts, packages/server/src/accounts-server.ts, packages/server/src/types/accounts-server-options.ts, packages/types/src/types/create-user-result.ts
Close https://github.com/accounts-js/accounts/issues/1260
=> feat: implement requireEmailVerification, fix ambiguousErrorMessages/enableAutologin relationship
